### ISSUE TITLE
As a < user >, I want < to be able to see the most actionable information about another user within the list view > so that < I am not constantly clicking into and out of user profile pages >

### ISSUE THREAD

**Issue by trm313** [Neoflash1979/coder-match#28]
**Conditions of Satisfactions**

- [x] Overlapping (or complimentary) tech preferences
- [x] User activity / responsiveness
- [x] User profile image
- [x] # of times 'favorited'

**Comment by Neoflash1979** [comment]
@trm313 Just a friendly reminder to check off the items in the conditions of satisfaction list as you complete them. Makes it easier for us to track your progress. Also, when you believe you are done working on your user story and the only thing left is a last review, you can go ahead and move the PR and the related issue to the Review/QA pipeline. There is a functionality in the PR that allows you to ask specific team members to review it, you can also go ahead and use that to let the others know you want them to review it.
